# Fluid 主题配置覆盖（参考：https://github.com/fluid-dev/hexo-theme-fluid）

favicon: /img/logo.svg
apple_touch_icon: /img/logo.svg

navbar:
  blog_title: "大象的小宇宙"
  menu:
    - { key: "home", link: "/" }
    - { name: "文章", link: "/blog/" }
    - { key: "about", link: "/about/" }
    - { name: "动态", link: "/moments/" }
    - { name: "友链", link: "/links/" }

index:
  banner_img: /img/bing-hero.jpg
  banner_img_height: 80
  banner_mask_alpha: 0.35
  slogan:
    enable: true
    text: "欢迎来到大象的小宇宙"

post:
  banner_img: /img/bing-hero.jpg
  banner_mask_alpha: 0.35
  math:
    enable: true
    specific: false
    engine: katex

page:
  banner_img: /img/bing-hero.jpg
  banner_mask_alpha: 0.35

about:
  enable: true
  banner_img: /img/bing-hero.jpg
  banner_mask_alpha: 0.35
  avatar: /img/hello8693.png
  name: "Hello8693"
  intro: "Hello8693。邮箱 hello8693@hello8693.xyz | QQ 1320998105"

social:
  enable: true
  github:
    icon: "iconfont icon-github"
    link: "https://github.com/Hello8693"
  email:
    icon: "iconfont icon-email"
    link: "mailto:hello8693@hello8693.xyz"
  qq:
    icon: "iconfont icon-qq"
    link: "tencent://message/?uin=1320998105&Site=&Menu=yes"

links:
  enable: true
  items: []

custom_js:
  - /js/bing-hero.js

custom_css:
  - /css/custom.css

footer:
  beian:
    enable: true
    icp_text: 鲁ICP备2022013359号-1
